"""add session_id to all tables

Revision ID: f1c53d97ab7f
Revises: adf3770e5b36
Create Date: 2026-05-28 22:48:33.968647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c53d97ab7f'
down_revision: Union[str, None] = 'adf3770e5b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('session_id', sa.String(length=50), server_default=sa.text("'demo'"), nullable=False))
    op.create_index(op.f('ix_forecasts_session_id'), 'forecasts', ['session_id'], unique=False)
    op.add_column('inventory_snapshots', sa.Column('session_id', sa.String(length=50), server_default=sa.text("'demo'"), nullable=False))
    op.create_index(op.f('ix_inventory_snapshots_session_id'), 'inventory_snapshots', ['session_id'], unique=False)
    op.add_column('sales_records', sa.Column('session_id', sa.String(length=50), server_default=sa.text("'demo'"), nullable=False))
    op.create_index(op.f('ix_sales_records_session_id'), 'sales_records', ['session_id'], unique=False)
    op.add_column('skus', sa.Column('session_id', sa.String(length=50), server_default=sa.text("'demo'"), nullable=False))
    op.create_index(op.f('ix_skus_session_id'), 'skus', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skus_session_id'), table_name='skus')
    op.drop_column('skus', 'session_id')
    op.drop_index(op.f('ix_sales_records_session_id'), table_name='sales_records')
    op.drop_column('sales_records', 'session_id')
    op.drop_index(op.f('ix_inventory_snapshots_session_id'), table_name='inventory_snapshots')
    op.drop_column('inventory_snapshots', 'session_id')
    op.drop_index(op.f('ix_forecasts_session_id'), table_name='forecasts')
    op.drop_column('forecasts', 'session_id')
    # ### end Alembic commands ###
